variables:
  LATEX_IMAGE: leplusorg/latex:latest

build:
  image: $LATEX_IMAGE
  script:
    - latexmk -f -pdf
    - mv main.pdf "The Goblin Scrolls.pdf"

  artifacts:
    paths:
      - "The Goblin Scrolls.pdf"
